// J2.L.P0006 - My Text Editor (MTE)

import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author SE130460
 */
public class ReplaceDialog extends javax.swing.JDialog
{
//    MyTextEditor parent = (MyTextEditor) this.getParent();    // Đứng trên cửa sổ con, gọi cửa sổ cha
//    String parentText = parent.txtContent.getText();          // Tại sao để biến toàn cục ở đây thì chỉ
//    String selectedText = parent.txtContent.getSelectedText();    // Find đc 1 lần duy nhất nhưng nếu
                                                // khai báo ở từng nút thì nó lại find đc đến hết luôn???
    
    public ReplaceDialog(java.awt.Frame parent, boolean modal)
    {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        setTitle("Replace");
        btnFind.setEnabled(false);
        btnFind.setVisible(false);
        btnReplace.setEnabled(false);
        btnReplaceAll.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtFind = new javax.swing.JTextField();
        btnFind = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtReplace = new javax.swing.JTextField();
        btnReplace = new javax.swing.JButton();
        btnReplaceAll = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setFocusable(false);
        setType(java.awt.Window.Type.POPUP);

        jLabel1.setText("Find what:");

        txtFind.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtFindKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtFindKeyTyped(evt);
            }
        });

        btnFind.setText("Find Next");
        btnFind.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFindActionPerformed(evt);
            }
        });

        jLabel2.setText("Replace with:");

        txtReplace.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtReplaceKeyReleased(evt);
            }
        });

        btnReplace.setText("Replace");
        btnReplace.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReplaceActionPerformed(evt);
            }
        });

        btnReplaceAll.setText("Replace All");
        btnReplaceAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReplaceAllActionPerformed(evt);
            }
        });

        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(txtFind, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtReplace, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnReplace, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnFind, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnReplaceAll, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCancel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtFind, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnFind))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtReplace, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnReplace))
                .addGap(18, 18, 18)
                .addComponent(btnReplaceAll)
                .addGap(18, 18, 18)
                .addComponent(btnCancel)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private boolean search(String text,char keyword,int start,int end)
    {
        for(int i=start;i<=end;i++)
            if(text.charAt(i)==keyword)
              return  true;
        return false;
    }
    private void btnFindActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFindActionPerformed
//            String keyword = txtFind.getText();
//            int fromIndex = 0;  // Vtrí bắt đầu tìm

        // Nút này để tìm nhưng ko trả về kết quả vtrí đc nên tôi nghĩ tôi ko cần dùng đến nút này đâu! .-.
        // Hiện tại, để bài cho dễ và kịp nộp bài thì xoá luôn nút Find đi.
        String keyword = txtFind.getText();
        MyTextEditor parent = (MyTextEditor) this.getParent();    // Đứng trên cửa sổ con, gọi cửa sổ cha
        String parentText = parent.txtContent.getText();
        int fromIndex = 0;  // Vtrí bắt đầu tìm
        String selectedText = parent.txtContent.getSelectedText();

        if (selectedText != null)   // Văn bản đã đc chọn trước đó
        {
            fromIndex = parent.txtContent.getSelectionEnd();  // Vtrí ngay sau chữ vừa đc chọn <=> vị trí bắt đầu tìm tiếp
        }
        int posFound = parentText.indexOf(keyword, fromIndex);  // Tìm keyword từ vtrí index, kết quả vtrí tìm thấy trả về result
        if (posFound >= 0)
        {
            if(search(parentText, '\n', fromIndex, posFound) == true)
                    posFound -= /*row * 2*/1;    // Chỗ này cứ sau mỗi 1 lần phải trừ 2, 4, 6, 8,... chứ ko trừ cố định 1 con
                parent.txtContent.select(posFound, posFound + keyword.length());    // số 2 đc.
        }
        else
            JOptionPane.showMessageDialog(this, "Cannot find \"" + keyword + "\"");
    }//GEN-LAST:event_btnFindActionPerformed

    private void btnReplaceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReplaceActionPerformed
        MyTextEditor parent = (MyTextEditor) this.getParent();    // Đứng trên cửa sổ con, gọi cửa sổ cha
        String parentText = parent.txtContent.getText();
        
        if (parentText.contains(txtFind.getText()))
        {
            parent.txtContent.setText(parentText.replaceFirst(txtFind.getText(), txtReplace.getText()));
//            parent.txtContent.setText(parentText.replaceFirst(selectedText, txtReplace.getText()));   // NullPointer
            btnFindActionPerformed(evt);    // Cái này để cho giống Notepad, thay xong rồi tìm tiếp
        }
        else
            JOptionPane.showMessageDialog(this, "Cannot find \"" + txtFind.getText() + "\"");
    }//GEN-LAST:event_btnReplaceActionPerformed

    private void btnReplaceAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReplaceAllActionPerformed
        MyTextEditor parent = (MyTextEditor) this.getParent();    // Đứng trên cửa sổ con, gọi cửa sổ cha
        String parentText = parent.txtContent.getText();
        
        if (parentText.contains(txtFind.getText()))
            parent.txtContent.setText(parentText.replaceAll(txtFind.getText(), txtReplace.getText()));
        else
            JOptionPane.showMessageDialog(this, "Cannot find \"" + txtFind.getText() + "\"");
    }//GEN-LAST:event_btnReplaceAllActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelActionPerformed

    private void txtFindKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFindKeyTyped
        // Ko biết tại sao nhưng cái KeyTyped này nó bắt phải đánh từ 2 kí tự trở lên thì mới enable cái nút còn ko thì vẫn bị disable
//        if (txtFind.getText().isEmpty())    // Ko có gì trong ô thì ẩn nút đi, ko cho tìm
//            btnFind.setEnabled(false);
//        else       // Phải nhập gì đó vào ô tìm kiếm rồi thì mới cho tìm
//            btnFind.setEnabled(true);
    }//GEN-LAST:event_txtFindKeyTyped

    private void txtFindKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFindKeyReleased
        if (txtFind.getText().isEmpty())    // Ko có gì trong ô thì ẩn nút đi, ko cho tìm
            btnFind.setEnabled(false);
        else       // Phải nhập gì đó vào ô tìm kiếm rồi thì mới cho tìm
            btnFind.setEnabled(true);
    }//GEN-LAST:event_txtFindKeyReleased

    private void txtReplaceKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtReplaceKeyReleased
        if (txtReplace.getText().isEmpty())
        {
            btnReplace.setEnabled(false);
            btnReplaceAll.setEnabled(false);
        }
        else
        {
            btnReplace.setEnabled(true);
            btnReplaceAll.setEnabled(true);
        }
    }//GEN-LAST:event_txtReplaceKeyReleased

//    private int posFound()    // Nghiên cứu sau
//    {
//        int pos = 0;
//        String keyword = txtFind.getText();
//        MyTextEditor parent = (MyTextEditor) this.getParent();    // Đứng trên cửa sổ con, gọi cửa sổ cha
//        String parentText = parent.txtContent.getText();
//        int fromIndex = 0;  // Vtrí bắt đầu tìm
//        String selectedText = parent.txtContent.getSelectedText();
//
//        if (selectedText != null)   // Văn bản đã đc chọn trước đó
//        {
//            fromIndex = parent.txtContent.getSelectionEnd();  // Vtrí ngay sau chữ vừa đc chọn <=> vị trí bắt đầu tìm tiếp
//        }
//        int posFound = parentText.indexOf(keyword, fromIndex);  // Tìm keyword từ vtrí index, kết quả vtrí tìm thấy trả về result
//        if (posFound >= 0)
//        {
//            if(search(parentText, '\n', fromIndex, posFound) == true)
//                    posFound -= /*row * 2*/1;    // Chỗ này cứ sau mỗi 1 lần phải trừ 2, 4, 6, 8,... chứ ko trừ cố định 1 con
//                parent.txtContent.select(posFound, posFound + keyword.length());    // số 2 đc.
//        }
//        else
//            JOptionPane.showMessageDialog(this, "Cannot find \"" + keyword + "\"");
//            
//        return pos;
//    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FindDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FindDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FindDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FindDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FindDialog dialog = new FindDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnFind;
    private javax.swing.JButton btnReplace;
    private javax.swing.JButton btnReplaceAll;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField txtFind;
    private javax.swing.JTextField txtReplace;
    // End of variables declaration//GEN-END:variables
}